# Generated by Django 3.1.1 on 2020-09-28 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200919_0846'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='bio',
            field=models.TextField(null=True, verbose_name='Biography'),
        ),
        migrations.AddField(
            model_name='workofart',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='workofart',
            name='rating',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Rating'),
        ),
    ]
