# Generated by Django 3.1.1 on 2020-09-28 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200928_1359'),
    ]

    operations = [
        migrations.AddField(
            model_name='workofart',
            name='image',
            field=models.URLField(null=True, verbose_name='Image URl'),
        ),
    ]
